{
 "title": "Eth2 Merge Kurtosis Module Dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Replay Blocks Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "per min" } },
   "targets": [
    {
     "expr": "rate(replay_blocks_count_sum{job=~\"cl-.*-prysm-geth\"}[1m])",
     "legendFormat": "{{job}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Beacon Head Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "beacon_head_slot{job=~\"cl-.*-prysm-geth|cl-*.-lighthouse-geth\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "finalized epoch head",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{job=~\"cl-.*-prysm-geth|cl-*.-lighthouse-geth\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Prysm Total Mem inuse",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"cl-.*-prysm-geth\"}+go_memstats_heap_inuse_bytes{job=~\"cl-.*-prysm-geth\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Prysm Stack Mem Inuse",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"cl-.*-prysm-geth\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Att Cache Hit %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(attestation_cache_hit{job=~\"cl-.*-prysm-geth\"}[1m])/(rate(attestation_cache_miss{job=~\"cl-.*-prysm-geth\"}[1m])+rate(attestation_cache_hit{job=~\"cl-.*-prysm-geth\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Next Slot Cache Hit %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(next_slot_cache_hit{job=~\"cl-.*-prysm-geth\"}[1m])/(rate(next_slot_cache_hit{job=~\"cl-.*-prysm-geth\"}[1m])+rate(next_slot_cache_miss{job=~\"cl-.*-prysm-geth\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Partipants",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_target_attesting_gwei_total/beacon_participation_prev_epoch_active_gwei_total"
    },
    {
     "expr": "beacon_previous_live_validators / beacon_previous_active_validators"
    },
    {
     "expr": "beacon_previous_correct_validators / beacon_previous_active_validators"
    }
   ]
  },
  {
   "title": "Deposits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "beacon_processed_deposits_total{job=~\"cl-4-prysm-geth\"}",
     "legendFormat": "Deposits Processed"
    },
    {
     "expr": "beacondb_all_deposits{job=~\"cl-4-prysm-geth\"}",
     "legendFormat": "All Deposits"
    }
   ]
  },
  {
   "title": "Hot State Cache Hit %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(hot_state_cache_hit{job=~\"cl-.*-prysm-geth\"}[1m])/(rate(hot_state_cache_hit{job=~\"cl-.*-prysm-geth\"}[1m])+rate(hot_state_cache_miss{job=~\"cl-.*-prysm-geth\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers{}", "legendFormat": "{{job}}" }
   ]
  }
 ]
}